LaurierHawkHacks/Landing

src/App.js
src/components/Navbar.js

Adds a typeform embed to the 'Apply Now' link in the Navbar, and adds the MLH banner.

Add typeform link & MLH banner to navbar

---

src/components/meet_the_team/MeetTheTeam.js
src/components/meet_the_team/TeamMember.js

- Card styling
- Description/Bio overlay on hover

Meet the team

---

src/components/meet_the_team/TeamMember.js

improving hover animations on team member cards

Improve hover animations

---

src/App.js
src/components/schedule/ScheduleEvent.js
src/components/schedule/ScheduleSection.js
src/data/scheduleData.json

Schedule section

---

index.html
package.json
pnpm-lock.yaml
src/index.css
tailwind.config.js

Fixes #30
- By default font-weight is 400.
- Tailwind was not installed to project so i did that
- Font typography update should be the next issue

Setup font family in Tailwind

---

package.json
pnpm-lock.yaml
prettier.config.mjs
src/components/Accordion/Accordion.tsx
src/components/Accordion/AccordionItem.tsx
src/components/index.tsx
src/components/sections/FAQ.section.tsx
src/pages/Landing.tsx

Create FAQ Section that contain a FAQ heading and an accordion
Checklist:

Create FAQ section and Accordion Component

---

src/components/sections/Footer.section.tsx

Issue: https://github.com/LaurierHawkHacks/Landing/issues/56
Additional items to footer

[Refactor] Add code of conduct and copyright to footer

---

src/components/sections/Hero.section.tsx
src/components/sections/Info.section.tsx

Changed the color for top of info section and removed the bottom padding for Hero section.
Also, I'm not sure why when I save the file, Prettier reformats the tabbing like that...
Update: I realized its the prettierrc.cjs file, the tab-width was set to 4.

Fix: hero to info section padding

---

src/components/sections/Info.section.tsx

This was super quick, but I guess it will give me a good idea of what you guys might be looking for :) Let me know what you guys think and if anything should be adjusted.

Add: responsive styling

---

src/index.css

Issue: https://github.com/LaurierHawkHacks/Landing/issues/102
1. header
2. button
3. link
4. button and link state

feature: create base, component and utilities styling

---

src/components/Navbar/Menu.tsx
src/components/Navbar/NavItems.tsx
src/components/Navbar/Navbar.tsx

Bug: https://github.com/LaurierHawkHacks/Landing/issues/124
Since the brand color in tailwind.config has updated, I have to update the text color in navbar as well.

Fix: update the color

---

src/components/index.tsx
src/pages/Landing.tsx

🛠️ Fix Section Imports
🔍 **What's Included**
- Corrected the import statement in `Landing.tsx` to include `SponsorSection`. (oops 😭)
📁 Files Affected:
- `src/components/index.tsx`
- `src/pages/Landing.tsx`

Fix section imports

---

pnpm-lock.yaml
src/components/Navbar/NavItems.tsx
src/components/Navbar/Navbar.tsx
src/components/sections/About.section.tsx
src/components/sections/Sponsor.section.tsx
src/components/sections/Team.section.tsx

**Todo:**
**Note:**
- About section is kinda weird, it smooth scrolls to the stats not the actual text with the about info (See image below)
- Wondering if maybe we add another button for stats and another one for about. Thoughts?

Fixed nav links

---

src/assets/team/meet-the-team-building-right.svg

Issue: #150 
The waterfall didn't get cut off anymore!

Fix: update the background in team section

---

src/components/sections/SponsorFAQ.section.tsx

Issue: #162 
Branch: [fix/162/max-width-for-each-section-is-not-aligned](https://github.com/LaurierHawkHacks/Landing/compare/main...fix/162/max-width-for-each-section-is-not-aligned?expand=1)
Note: I only change the max-width of the faq section, the other changes are what prettier done

Style: consistent max-width

---

src/components/sections/Contact.section.tsx
src/components/sections/SponsorFAQ.section.tsx

Issue: #152 
Branch: [fix/152/bird-face-get-distorted-when-screen-is-about-1080px](https://github.com/LaurierHawkHacks/Landing/compare/main...fix/152/bird-face-get-distorted-when-screen-is-about-1080px?expand=1)
Lmk what weird stuff happen to the bird, I think so far so good
Note: I didn't update the branch name,  will do it next time

Fix: no more distorted birdy

---

src/assets/team/meet-the-team-building-right.svg
src/components/sections/TeamFAQ.section.tsx

Fix: #181 
Branch: https://github.com/LaurierHawkHacks/Landing/compare/main...bug/181/bug-horizontal-overflow?expand=1
Ping: @AmirAgassi @aidantrabs @GabeDiniz @norachams @ABCodez

Fix: no more overflow in team section

---

src/components/Navbar/NavItems.tsx

Fix: anchor space fix in contact section

---

src/components/sections/data/faqData.ts

Fix: update the date in faq tab

---

src/components/sections/TeamFAQ.section.tsx

Issue: #204 
Note: lmk if the background needs to change @aidantrabs

fix: background gradient in faq-team section

---

src/components/sections/Sponsor.section.tsx

There were some ts errors when trying to build the project.

fix ts errors in sponsor section

---

src/assets/index.tsx
src/components/LoadingAnimation.tsx
src/components/Navbar/Navbar.tsx
src/components/sections/TeamFAQ.section.tsx

Fix asset imports in components and exports in index

---

src/components/SocialIcons.tsx

Fixes #223 
- fixed the hover animation
- got rid of Devpost as we don't have it setup yet / isn't that important tbh

Update social icons to be closer to the Figma design

---

src/components/SocialIcons.tsx
src/utils/SocialLinks.tsx
src/utils/SponsorLinks.tsx
src/utils/index.tsx

Fixes #244 
The rest of the URLs should be added by whoever is working on the sponsor/partner section

Abstract links to utilities

---

src/components/Accordion.tsx
src/components/sections/TeamFAQ.section.tsx
src/components/sections/data/faqData.ts

Accordian with updated Questions

---

src/components/sections/HeroStats.section.tsx

feat: adding background and spacing at the hero section

---

src/components/sections/Sponsor.section.tsx

Issue:#272 
Branch: [fix/272/sponsors-spacing](https://github.com/LaurierHawkHacks/Landing/compare/main...fix/272/sponsors-spacing?expand=1)
What has changed?
- Just redo the space styling in sponsor section, nothing much.
- I have made sure that the analytic component is kept intact.
File changed:
src/components/sections/Sponsor.section.tsx

fix: sponsor's spacing
